name: calculadora_imc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17
  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.2
  cached_network_image: ^3.2.1
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  loader_overlay: ^2.0.7
  password_validators:
    git:
      url: https://github.com/bmsrangel/flutter_password_validators.git
      ref: main
  validatorless: ^1.2.1
  geolocator: ^8.2.1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  faker: ^2.0.0
  firebase_auth_mocks: ^0.8.4
  firebase_storage_mocks: ^0.5.0
  mocktail: ^0.3.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
