import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_modular/flutter_modular.dart';

import 'app/app_module.dart';
import 'app/app_widget.dart';
import 'firebase_options.dart';

const host = '192.168.1.102';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  /* DefaultFirebaseOptions.currentPlatform is automatically generated by the 
  Flutterfire CLI*/
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(ModularApp(
    module: AppModule(),
    child: const AppWidget(),
  ));
}
